import type {
  Contract,
  Message,
  MessageThread,
  Notification,
  Project,
  Proposal,
  Transaction,
  User,
} from "@/types";

export const mockUsers: Record<string, User> = {
  client: {
    id: "usr-elena",
    fullName: "Elena Rostova",
    email: "elena.rostova@techcorp.io",
    role: "client",
    title: "Enterprise Lead",
    company: "TechCorp Labs",
    timezone: "UTC-05:00 Eastern Time (US & Canada)",
    verified: false,
  },
  freelancer: {
    id: "usr-alex",
    fullName: "Alex Vance",
    email: "alex.vance@studio-kollab.io",
    role: "freelancer",
    title: "Sr. Systems Designer",
    verified: true,
  },
  admin: {
    id: "usr-marcus",
    fullName: "Marcus Vance",
    email: "marcus.vance@kollab.io",
    role: "admin",
    title: "Principal Auditor",
    verified: true,
  },
};

export const mockProjects: Project[] = [
  {
    id: "prj-84920",
    code: "PRJ-84920",
    title: "Fintech Mobile Banking App Redesign",
    description:
      "TechCorp is looking for an experienced Senior Product & Systems Designer to lead the end-to-end UX/UI architecture for our flagship consumer mobile banking and automated micro-investing application.",
    category: "Web & Mobile Development",
    budget: 14000,
    paymentStructure: "fixed",
    status: "in_progress",
    proposalsCount: 18,
    deadline: "2024-10-28",
    clientName: "Elena Rostova",
    clientCompany: "TechCorp Labs",
    clientRating: 4.98,
    skills: ["Figma", "Design Systems", "iOS HIG", "Fintech", "Prototyping"],
    postedAt: "2024-09-05",
    milestones: [
      {
        id: "m1",
        title: "Design Discovery & Low-Fi Wireframes",
        description: "User journey maps, architectural diagrams, 24 wireframe screen blueprints approved.",
        amount: 3000,
        status: "completed",
        releasedDate: "2024-09-20",
      },
      {
        id: "m2",
        title: "Design System & Component Tokens",
        description: "Figma component library, light/dark mode elevation scales, typography tokens.",
        amount: 3500,
        status: "completed",
        releasedDate: "2024-10-05",
      },
      {
        id: "m3",
        title: "Biometric Auth & Account Dashboard Flows",
        description: "Design and prototype full biometric authentication flow (FaceID/Fingerprint), fallback PIN entry, and responsive Account Dashboard.",
        amount: 3500,
        status: "submitted",
        dueDate: "2024-10-20",
      },
      {
        id: "m4",
        title: "Transfer, Pay & Transaction History Flows",
        description: "P2P transfers, bill pay checkout, multi-currency wallet conversion screens.",
        amount: 2500,
        status: "funded",
        dueDate: "2024-11-05",
      },
      {
        id: "m5",
        title: "Interactive Prototype & Final Handoff",
        description: "Micro-interactions in Protopie, developer inspection spec sheet, design documentation.",
        amount: 1500,
        status: "not_funded",
        dueDate: "2024-11-20",
      },
    ],
  },
  {
    id: "prj-90311",
    code: "PRJ-90311",
    title: "AI Copilot Chrome Extension & LLM Integration",
    description:
      "We are building a production-grade enterprise Chrome Extension acting as a persistent AI Copilot across web workflows. The application must comply entirely with Chrome Manifest V3 regulations.",
    category: "Web & Browser Dev",
    budget: 8500,
    paymentStructure: "fixed",
    status: "open",
    proposalsCount: 24,
    deadline: "2024-11-30",
    clientName: "Elena Rostova",
    clientCompany: "TechCorp Labs",
    clientRating: 4.98,
    skills: ["TypeScript", "Chrome Extensions (Manifest V3)", "OpenAI API", "Anthropic Claude SDK", "Tailwind CSS", "React", "IndexedDB"],
    postedAt: "2024-10-12",
    milestones: [
      { id: "m1", title: "Extension Shell & Auth Integration", description: "Manifest V3 structure, persistent background service worker, Supabase auth handshake.", amount: 2500, status: "funded", dueDate: "2024-10-19" },
      { id: "m2", title: "Context Parsing & LLM Streaming", description: "DOM text extraction engine, client-side vector search, streaming SSE integration with OpenAI.", amount: 3500, status: "not_funded", dueDate: "2024-10-30" },
      { id: "m3", title: "Chrome Web Store Packaging & Docs", description: "Comprehensive end-to-end testing, bundle optimization under 4MB, Web Store audit sign-off.", amount: 2500, status: "not_funded", dueDate: "2024-11-06" },
    ],
  },
  {
    id: "prj-77140",
    code: "PRJ-77140",
    title: "Enterprise Design System v2.0",
    description: "Standardize the token pipeline across React, React Native, and web apps using Style Dictionary and Figma Variables.",
    category: "Design Systems",
    budget: 12000,
    paymentStructure: "hourly",
    status: "in_progress",
    proposalsCount: 14,
    deadline: "2024-12-01",
    clientName: "David Vance",
    clientCompany: "CloudScale Systems",
    clientRating: 4.8,
    skills: ["Figma Tokens", "Tailwind", "Storybook"],
    postedAt: "2024-09-18",
    milestones: [],
  },
  {
    id: "prj-99302",
    code: "PRJ-99302",
    title: "Stripe Billing Integration & Webhooks",
    description: "Idempotent webhook handling and subscription billing sync for a Node.js SaaS backend.",
    category: "Backend",
    budget: 3200,
    paymentStructure: "fixed",
    status: "draft",
    proposalsCount: 0,
    clientName: "Elena Rostova",
    clientCompany: "TechCorp Labs",
    clientRating: 4.98,
    skills: ["Node.js", "Webhooks", "Idempotency"],
    postedAt: "2024-10-24",
    milestones: [],
  },
];

export const mockProposals: Proposal[] = [
  {
    id: "prop-9402",
    projectId: "prj-90311",
    freelancerName: "Liam Henderson",
    freelancerTitle: "Senior Full-Stack & Chrome Extensions Specialist",
    rating: 4.98,
    reviewsCount: 42,
    location: "London, UK",
    bidAmount: 8200,
    deliveryDays: 18,
    coverLetter:
      "I have developed 4 commercial Chrome extensions with Manifest V3 and SSE streaming from OpenAI API. My solution ensures strict CSP compliance and sub-50ms DOM parsing.",
    skills: ["Chrome Extensions", "TypeScript", "OpenAI API", "Tailwind"],
    status: "shortlisted",
    submittedAt: "2024-10-13",
  },
  {
    id: "prop-7711",
    projectId: "prj-90311",
    freelancerName: "Priya Sharma",
    freelancerTitle: "Senior Frontend Architect & LLM Integration Engineer",
    rating: 5.0,
    reviewsCount: 29,
    location: "Toronto, CA",
    bidAmount: 7900,
    deliveryDays: 14,
    coverLetter:
      "Specialized in high-concurrency LLM streaming UIs, background service workers, and secure OAuth storage in browser extensions.",
    skills: ["React", "WebExtensions API", "TypeScript", "Anthropic SDK"],
    status: "interviewing",
    submittedAt: "2024-10-13",
  },
  {
    id: "prop-6644",
    projectId: "prj-90311",
    freelancerName: "Carlos Gomez",
    freelancerTitle: "JavaScript / Web Extension Developer",
    rating: 4.85,
    reviewsCount: 19,
    location: "Austin, USA",
    bidAmount: 8500,
    deliveryDays: 21,
    coverLetter:
      "Hello team, I reviewed your Chrome Extension specs. I have built 2 extensions that interact with local browser storage and invoke background fetch APIs.",
    skills: ["JavaScript", "Web Extensions", "DOM Parsing"],
    status: "pending",
    submittedAt: "2024-10-14",
  },
];

export const mockContracts: Contract[] = [
  {
    id: "cnt-84920",
    projectId: "prj-84920",
    projectTitle: "Fintech Mobile Banking App Redesign",
    clientName: "Elena Rostova",
    freelancerName: "Alex Vance",
    totalValue: 14000,
    paidToDate: 6500,
    inEscrow: 3500,
    paymentStructure: "fixed",
    status: "active",
    startedAt: "2024-09-05",
    targetCompletion: "2024-11-20",
    milestones: mockProjects[0].milestones,
  },
];

export const mockTransactions: Transaction[] = [
  { id: "TXN-90214", projectTitle: "Fintech Mobile Banking App", counterpartyName: "Elena Vance", description: "Milestone 2: Design System & Tokens", amount: 3500, method: "VISA •••• 4242", status: "completed", date: "2024-10-05" },
  { id: "TXN-89842", projectTitle: "AI Copilot Chrome Extension", counterpartyName: "Kollab Vault Escrow", description: "Escrow Deposit: Milestone 1", amount: 2500, method: "ACH •••• 8910", status: "completed", date: "2024-10-12" },
  { id: "TXN-88410", projectTitle: "Fintech Mobile Banking App", counterpartyName: "Elena Vance", description: "Milestone 1: Wireframes", amount: 3000, method: "VISA •••• 4242", status: "completed", date: "2024-09-20" },
  { id: "TXN-87612", projectTitle: "Enterprise Design System v2.0", counterpartyName: "Marcus Chen", description: "Weekly Hourly Payout (40 hrs)", amount: 3800, method: "VISA •••• 4242", status: "completed", date: "2024-09-18" },
  { id: "TXN-85114", projectTitle: "B2B Analytics Portal Dashboard", counterpartyName: "Dev Studio LLC", description: "Escrow Refund (Terminated)", amount: -4500, method: "VISA •••• 4242", status: "completed", date: "2024-08-15" },
];

export const mockThreads: MessageThread[] = [
  { id: "thr-1", participantName: "Elena Rostova", projectTitle: "Fintech Mobile Banking App", lastMessagePreview: "Alex, please ensure the dark mode high-contrast variant...", unreadCount: 2, lastActivityAt: "2m ago" },
  { id: "thr-2", participantName: "Synthetix AI", projectTitle: "AI Copilot Chrome Extension", lastMessagePreview: "Are you available for a 15-min...", unreadCount: 1, lastActivityAt: "2h ago" },
  { id: "thr-3", participantName: "CloudScale Systems", projectTitle: "Enterprise Design System", lastMessagePreview: "Contract signed and escrow funded...", unreadCount: 0, lastActivityAt: "1d ago" },
  { id: "thr-4", participantName: "MetricHQ", projectTitle: "SaaS Analytics Dashboard", lastMessagePreview: "Thanks for the final delivery packag...", unreadCount: 0, lastActivityAt: "3w ago" },
];

export const mockMessages: Message[] = [
  { id: "msg-1", threadId: "thr-1", senderName: "Alex Vance", senderIsSelf: true, content: "Thanks Elena! I've also incorporated the fallback PIN lockup recovery flow we discussed in the last sprint.", sentAt: "10:22 AM" },
  { id: "msg-2", threadId: "thr-1", senderName: "Elena Rostova", senderIsSelf: false, content: "Great. One note from our accessibility team: could you verify the AAA contrast ratios on the dark mode OLED surfaces before submitting?", sentAt: "10:45 AM" },
  { id: "msg-3", threadId: "thr-1", senderName: "Alex Vance", senderIsSelf: true, content: "Absolutely, already executed automated token tests. Here is the updated contrast audit spec:", sentAt: "11:02 AM" },
];

export const mockNotifications: Notification[] = [
  { id: "n1", title: "Milestone 2 Escrow Released ($3,500.00 USD)", description: "Elena Rostova (TechCorp Labs) approved Milestone 2 deliverables. Funds have been deposited directly into your Kollab Wallet.", category: "escrow", read: false, createdAt: "12 minutes ago", actionLabel: "View Wallet Balance" },
  { id: "n2", title: "Interview Request for AI Copilot Extension", description: "Synthetix AI shortlisted your proposal for PRJ-9104 and invited you to a technical discovery interview.", category: "proposal", read: false, createdAt: "1 hour ago", actionLabel: "Respond to Interview" },
  { id: "n3", title: "New Contract Offer Created", description: "CloudScale Systems initiated a fixed-price contract for Enterprise Design System v2.0 ($12,000.00 total).", category: "system", read: false, createdAt: "3 hours ago", actionLabel: "Review Contract Offer" },
  { id: "n4", title: "Milestone 3 Submission Reminder", description: "Target delivery for Biometric Auth & Account Dashboard is in 48 hours (Oct 20, 2024).", category: "system", read: false, createdAt: "5 hours ago", actionLabel: "Submit Milestone Work" },
];
